### ISSUE TITLE
Data Augmentation Code

### ISSUE THREAD

**Issue by PengWenChen** [DaniMS-ZGZ/Panoramic-CNN-360-Saliency#1]
Hi,

Thanks for your kindly sharing of your code.
However, there's no data augmentation code mentioned in paper. (7 data augmentation)
Could you also share the pre-processing code here?
By the way, I've tried to reproduce the score in paper.
But the output color seems to be opposite. (black to white, white to black)
Is there any post-processing steps to the output from the model?

Many thanks.

gt
![image_00_gt](https://user-images.githubusercontent.com/37527080/89388327-720ecd80-d736-11ea-85c2-dc1afbb5444c.jpg)

my reproduce result
![image_00_sphere](https://user-images.githubusercontent.com/37527080/89388360-7c30cc00-d736-11ea-9cd8-097a1314fb80.jpg)

**Comment by DaniMS-ZGZ** [comment]
Hi:

Thanks a lot for taking a look into this.

_About the augmentation code_: I have just added a new file into the repository. I had not realized I forgot about the augmentation script, because it was done in a pre-processing stage, hance it was in another directory. 

There is now a file called "**augment.py**" which includes the augmentation code with a brief explanation about how to use it. You can just run the script with "**python augment.py**" in a directory with an "**img/**" folder incluuding both the RGB and saliency map for each scene alphabetically ordererd like: RGBscene1 - SALscene1 - RGBscene2 - SALscene2 - etc.

This will create two output folders, one including the augmented RGBs and another one including the augmented saliency maps.

_About the output color_: There is no need of a post-processing stage: color levels should be correct. 

Regards,

**Comment by PengWenChen** [comment]
Got it.
Thanks for the response!
